model_name: SaltDDN
model_hparams:
  encoder_name: resnet101
  densenet_num_layers: [4,6,6,4]
  classes: 2
optimizer_name: Adam
optimizer_hparams:
  lr: 0.0005
  weight_decay: 0.0001
lr_scheduler_name: step
lr_scheduler_hparams:
  lr_scheduler_step_size: 10
  lr_scheduler_gamma: 0.5
aux_params:
  alpha: 0.5
  beta: 0.2
  gama: 0.3