model_name: denseaspp
model_hparams:
  activation: relu
  classes: 2
optimizer_name: Adam
optimizer_hparams:
  lr: 0.01
  weight_decay: 0.0001
lr_scheduler_name: step
lr_scheduler_hparams:
  lr_scheduler_step_size: 100
  lr_scheduler_gamma: 0.5