model_name: fcn
model_hparams:
  activation: relu
  classes: 2
optimizer_name: Adam
optimizer_hparams:
  lr: 0.01
  weight_decay: 0.0001
lr_scheduler_name: milestones
lr_scheduler_hparams:
  milestones: [100,200]
  gamma: 0.1
