model_name: SaltDDN
model_hparams:
  encoder_name: resnet101
  decoder_channels: 256
  classes: 2
optimizer_name: Adam
optimizer_hparams:
  lr: 0.08
  weight_decay: 0.001
lr_scheduler_name: plateau
lr_scheduler_hparams:
  lr_scheduler_patience: 5
  lr_scheduler_gamma: 0.5